---
# Provisioning infrastructure with Terraform
- name: Terraform provisioning
  shell: |
    chdir="{{ terraform_dir }}"
    terraform init
    terraform validate
    terraform plan
    terraform apply --auto-approve

- name: Get instance AWS IPs
  shell: |
    chdir="{{ terraform_dir }}"
    terraform output -raw instance_public_ip
  register: instance_public_ip

- name: Store instance IP in hosts file
  shell: |
    echo '[instances]' >> ~/project/ansible/hosts
    echo "{{ instance_public_ip }}" >> ~/project/ansible/hosts
